# Generated by Django 5.2.17 on 2026-10-04 04:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscription_comp_fields'),
        ('moderation', '0007_permanent_ban'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('stripe_price_setting', models.CharField(max_length=64)),
                ('min_role', models.CharField(default='provisional', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(max_length=128)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='comp_reason',
            field=models.CharField(blank=True, choices=[('staff', 'Staff'), ('founding', 'Founding'), ('other', 'Other')], max_length=16),
        ),
        migrations.AddField(
            model_name='subscription',
            name='comped_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='restricted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='kind',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('ban_reversal', 'Ban Reversal'), ('extra', 'Extra'), ('gift', 'Gift')], max_length=16),
        ),
        migrations.AlterField(
            model_name='charge',
            name='stripe_payment_intent_id',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('charge', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entitlement', to='billing.charge')),
                ('revoked_by_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='moderation.moderationaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to=settings.AUTH_USER_MODEL)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='billing.extra')),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('accepted', 'Accepted')], default='paid', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('charge', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gift', to='billing.charge')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gifts_received', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gifts_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LapsePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('restricted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lapse_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user',), name='one_open_lapse_per_user')],
            },
        ),
    ]
