# Generated by Django 5.2.17 on 2026-10-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('ok', models.BooleanField()),
                ('error', models.TextField(blank=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['job', 'ok', 'started_at'], name='core_jobrun_job_9b6334_idx')],
            },
        ),
    ]
