# Generated by Django 5.2.17 on 2026-10-05 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


OLD_TO_NEW = {"pending": "open", "in_progress": "building", "completed": "done", "rejected": "withdrawn"}


def rename_statuses(apps, schema_editor):
    DataRequest = apps.get_model("core", "DataRequest")
    for old, new in OLD_TO_NEW.items():
        DataRequest.objects.filter(status=old).update(status=new)


def restore_statuses(apps, schema_editor):
    DataRequest = apps.get_model("core", "DataRequest")
    for old, new in OLD_TO_NEW.items():
        DataRequest.objects.filter(status=new).update(status=old)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='deferral_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='deferred_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='link_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='link_token_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='posts_to_remove',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='watermark_seed',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='datarequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('deferred', 'Deferred'), ('withdrawn', 'Withdrawn'), ('building', 'Building'), ('ready', 'Ready'), ('done', 'Done')], default='open', max_length=16),
        ),
        migrations.AddIndex(
            model_name='datarequest',
            index=models.Index(fields=['kind', 'status'], name='core_datare_kind_189367_idx'),
        ),
        migrations.RunPython(rename_statuses, restore_statuses),
    ]
