# Generated by Django 5.2.17 on 2026-10-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_assignment_and_session_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityrecord',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
