# Generated by Django 5.2.17 on 2026-10-04 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_block'),
        ('boards', '0006_avatar_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='boards.attachment'),
        ),
        migrations.AddField(
            model_name='user',
            name='caption',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
