# Generated by Django 5.2.17 on 2026-10-04 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_avatar_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='approx_location',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='device_fingerprint',
        ),
        migrations.AddField(
            model_name='usersession',
            name='browser_family',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='usersession',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='usersession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='os_family',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='usersession',
            name='revoke_reason',
            field=models.CharField(blank=True, choices=[('signed_out', 'Signed Out'), ('signed_out_by_member', 'Signed Out By Member'), ('concurrent_location', 'Concurrent Location'), ('factor_reset', 'Factor Reset'), ('expired', 'Expired'), ('idle', 'Idle')], max_length=24),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='watermark_seed',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
