# Generated by Django 5.2.17 on 2026-10-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_session_binding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emoji_display',
            field=models.CharField(choices=[('images', 'Images'), ('still', 'Still'), ('names', 'Names')], default='images', max_length=8),
        ),
    ]
