# Generated by Django 5.2.17 on 2026-10-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_removal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='colour_scheme',
            field=models.CharField(choices=[('device', 'Device'), ('light', 'Light'), ('dark', 'Dark')], default='device', max_length=8),
        ),
    ]
