# Generated by Django 5.2.17 on 2026-10-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_colour_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tombstone_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
