from django.urls import path

from boards import emoji_views, message_views, views

urlpatterns = [
    path("", views.forum_index, name="home"),
    path("f/<slug:slug>/", views.subforum_page, name="subforum"),
    path("f/<slug:slug>/new/", views.new_thread, name="new_thread"),
    path("t/<int:pk>/", views.thread_page, name="thread"),
    path("t/<int:pk>/reply/", views.reply, name="reply"),
    path("t/<int:pk>/title/", views.edit_title, name="edit_title"),
    path("t/<int:pk>/titles/", views.title_revisions, name="title_revisions"),
    path("t/<int:pk>/move/", views.move_thread, name="move_thread"),
    path("t/<int:pk>/end/<str:how>/", views.end_thread, name="end_thread"),
    path("t/<int:pk>/<str:what>/", views.toggle, name="thread_toggle"),
    path("p/<int:pk>/", views.post_link, name="post_link"),
    path("p/<int:pk>/edit/", views.edit_post, name="edit_post"),
    path("p/<int:pk>/delete/", views.delete_post, name="delete_post"),
    path("p/<int:pk>/revisions/", views.post_revisions, name="post_revisions"),
    path("p/<int:pk>/<str:decision>/", views.moderate_post, name="moderate_post"),
    path("members/autocomplete/", views.mention_autocomplete, name="mention_autocomplete"),
    path("members/<slug:slug>/", views.member_profile, name="member_profile"),
    path("members/<slug:slug>/rap-sheet/", views.rap_sheet, name="rap_sheet"),
    path("members/<slug:slug>/block/", message_views.block, name="member_block"),
    path("messages/", message_views.inbox, name="inbox"),
    path("messages/new/", message_views.new_conversation, name="new_conversation"),
    path("messages/<int:pk>/", message_views.conversation, name="conversation"),
    path("messages/<int:pk>/send/", message_views.send, name="dm_send"),
    path("messages/<int:pk>/add/", message_views.add, name="dm_add"),
    path("messages/<int:pk>/leave/", message_views.leave, name="dm_leave"),
    path("messages/<int:pk>/remove/<int:user_pk>/", message_views.remove, name="dm_remove"),
    path("search/", views.search, name="search"),
    path("emoji/", emoji_views.emoji_list, name="emoji_list"),
    path("emoji/new/", emoji_views.emoji_new, name="emoji_new"),
    path("emoji/<int:pk>/image/", emoji_views.emoji_image, name="emoji_image"),
    path("emoji/<int:pk>/still/", emoji_views.emoji_still, name="emoji_still"),
    path("emoji/<int:pk>/retire/", emoji_views.emoji_retire, name="emoji_retire"),
    path("emoji/<int:pk>/<str:step>/", emoji_views.emoji_review, name="emoji_review"),
    path("emoji/refund/<int:pk>/", emoji_views.emoji_refund, name="emoji_refund"),
    path("settings/display/", emoji_views.display_settings, name="display_settings"),
    path("attachments/<int:pk>/", views.attachment, name="attachment"),
]
