# Generated by Django 5.2.17 on 2026-10-03 17:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DMAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_note', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dm_grants', to=settings.AUTH_USER_MODEL)),
                ('subject_users', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('note', 'Note'), ('warning', 'Warning'), ('hold', 'Hold'), ('suspension', 'Suspension'), ('read_only', 'Read Only'), ('ban', 'Ban'), ('ban_reversal', 'Ban Reversal'), ('sponsorship_transfer', 'Sponsorship Transfer'), ('sponsoring_suspension', 'Sponsoring Suspension')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('reversed', 'Reversed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('internal_reason', models.TextField()),
                ('public_summary', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='moderation.moderationaction')),
                ('related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderation_actions', to='boards.post')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('open', 'Open'), ('handled', 'Handled'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='boards.post')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('decided', 'Decided')], default='pending', max_length=16)),
                ('outcome', models.CharField(blank=True, choices=[('no_action', 'No Action'), ('warning', 'Warning'), ('sponsoring_suspension', 'Sponsoring Suspension'), ('ban', 'Ban')], max_length=24)),
                ('suspension_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('invitees_transfer', models.BooleanField(default=False)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('banned_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resulting_action', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='moderation.moderationaction')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsor_reviews', to=settings.AUTH_USER_MODEL)),
                ('triggering_action', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sponsor_review', to='moderation.moderationaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['target_user', 'kind', 'status'], name='moderation__target__7229f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='moderationaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'note'), _negated=True), ('is_public', False), _connector='OR'), name='notes_are_private'),
        ),
        migrations.AddConstraint(
            model_name='moderationaction',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('initiated_by')), _negated=True), _connector='OR'), name='approver_differs_from_initiator'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('post__isnull', False), ('user__isnull', False), _connector='OR'), name='report_has_subject'),
        ),
    ]
