# Generated by Django 5.2.17 on 2026-10-04 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_dm_participation_periods'),
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='escalated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='escalation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='kind',
            field=models.CharField(choices=[('post', 'Post'), ('member', 'Member'), ('dm', 'Dm'), ('flag_rate_limit', 'Flag Rate Limit'), ('flag_rapid_deletion', 'Flag Rapid Deletion'), ('flag_request_rate', 'Flag Request Rate')], default='post', max_length=24),
        ),
        migrations.AddField(
            model_name='report',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='outcome',
            field=models.CharField(blank=True, choices=[('action_taken', 'Action Taken'), ('no_action', 'No Action')], max_length=16),
        ),
        migrations.AddField(
            model_name='report',
            name='source',
            field=models.CharField(choices=[('member', 'Member'), ('system', 'System')], default='member', max_length=8),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(blank=True, choices=[('off_topic', 'Off-topic'), ('personal_attack', 'Personal attack'), ('spam', 'Spam'), ('private_information', 'Private information'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], default='open', max_length=16),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='moderation__status_2a84ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('source', 'system'), ('reporter__isnull', False), _connector='OR'), name='member_reports_have_reporter'),
        ),
    ]
