# Generated by Django 5.2.17 on 2026-10-04 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_dm_participation_periods'),
        ('moderation', '0002_report_queue_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationaction',
            name='decline_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='declined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='public_summary_draft',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='scope_subforum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='boards.subforum'),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='kind',
            field=models.CharField(choices=[('note', 'Note'), ('warning', 'Warning'), ('hold', 'Hold'), ('suspension', 'Suspension'), ('probation', 'Probation'), ('ban', 'Ban'), ('ban_reversal', 'Ban Reversal'), ('sponsorship_transfer', 'Sponsorship Transfer'), ('sponsoring_suspension', 'Sponsoring Suspension')], max_length=24),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('reversed', 'Reversed'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=16),
        ),
    ]
