# Generated by Django 5.2.17 on 2026-10-04 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_scope_subforums'),
        ('sponsorship', '0004_invitation_onboarding_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='related_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalations', to='moderation.moderationaction'),
        ),
        migrations.AddField(
            model_name='report',
            name='related_promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalations', to='sponsorship.promotion'),
        ),
        migrations.AlterField(
            model_name='report',
            name='kind',
            field=models.CharField(choices=[('post', 'Post'), ('member', 'Member'), ('dm', 'Dm'), ('escalation', 'Escalation'), ('flag_rate_limit', 'Flag Rate Limit'), ('flag_rapid_deletion', 'Flag Rapid Deletion'), ('flag_request_rate', 'Flag Request Rate')], default='post', max_length=24),
        ),
    ]
