# Generated by Django 5.2.17 on 2026-10-04 04:14

import accounts.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0006_escalation_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationaction',
            name='kind',
            field=models.CharField(choices=[('note', 'Note'), ('warning', 'Warning'), ('hold', 'Hold'), ('suspension', 'Suspension'), ('probation', 'Probation'), ('ban', 'Ban'), ('permanent_ban', 'Permanent Ban'), ('ban_reversal', 'Ban Reversal'), ('sponsorship_transfer', 'Sponsorship Transfer'), ('sponsoring_suspension', 'Sponsoring Suspension')], max_length=24),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('reversed', 'Reversed'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('annulled', 'Annulled')], default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='PermanentBanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', accounts.fields.EncryptedTextField(blank=True)),
                ('real_name', accounts.fields.EncryptedTextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('annulled_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='permanent_ban_record', to='moderation.moderationaction')),
            ],
        ),
    ]
