# Generated by Django 5.2.17 on 2026-10-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0009_extras_action_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='kind',
            field=models.CharField(choices=[('post', 'Post'), ('member', 'Member'), ('dm', 'Dm'), ('escalation', 'Escalation'), ('flag_rate_limit', 'Flag Rate Limit'), ('flag_rapid_deletion', 'Flag Rapid Deletion'), ('flag_request_rate', 'Flag Request Rate'), ('flag_concurrent_location', 'Flag Concurrent Location')], default='post', max_length=24),
        ),
    ]
