# Generated by Django 5.2.17 on 2026-10-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0010_concurrent_location_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationaction',
            name='kind',
            field=models.CharField(choices=[('note', 'Note'), ('warning', 'Warning'), ('hold', 'Hold'), ('suspension', 'Suspension'), ('probation', 'Probation'), ('ban', 'Ban'), ('permanent_ban', 'Permanent Ban'), ('avatar_reset', 'Avatar Reset'), ('extra_revocation', 'Extra Revocation'), ('extra_restoration', 'Extra Restoration'), ('ban_reversal', 'Ban Reversal'), ('sponsoring_suspension', 'Sponsoring Suspension')], max_length=24),
        ),
    ]
