# Generated by Django 5.2.17 on 2026-10-03 17:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_source', models.TextField()),
                ('body_html', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_held', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('mime', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='boards.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_source', models.TextField()),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='boards.post')),
            ],
        ),
        migrations.CreateModel(
            name='SubForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='boards.subforum')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('discussion', 'Discussion'), ('dm', 'Dm')], default='discussion', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked'), ('archived', 'Archived')], default='open', max_length=16)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_post_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threads_started', to=settings.AUTH_USER_MODEL)),
                ('subforum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='boards.subforum')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='boards.thread'),
        ),
        migrations.CreateModel(
            name='ThreadParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='boards.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thread_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['subforum', '-last_post_at'], name='boards_thre_subforu_fec6be_idx'),
        ),
        migrations.AddConstraint(
            model_name='thread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'dm'), ('subforum__isnull', True)), models.Q(('kind', 'discussion'), ('subforum__isnull', False)), _connector='OR'), name='dm_threads_have_no_subforum'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'created_at'], name='boards_post_author__545a17_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['thread', 'created_at'], name='boards_post_thread__01022c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(condition=models.Q(('is_held', True)), fields=['created_at'], name='post_held_queue'),
        ),
        migrations.AddConstraint(
            model_name='threadparticipant',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='one_participation_per_thread'),
        ),
    ]
