# Generated by Django 5.2.17 on 2026-10-04 00:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadTitleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='postrevision',
            name='is_redaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postrevision',
            name='purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postrevision',
            name='purged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subforum',
            name='kind',
            field=models.CharField(choices=[('regular', 'Regular'), ('graveyard', 'Graveyard'), ('classics', 'Classics')], default='regular', max_length=16),
        ),
        migrations.AddField(
            model_name='thread',
            name='end_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='ended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='origin_subforum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='boards.subforum'),
        ),
        migrations.AlterField(
            model_name='postrevision',
            name='body_source',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='subforum',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'regular'), _negated=True), fields=('kind',), name='one_graveyard_one_classics'),
        ),
        migrations.AddField(
            model_name='postquote',
            name='quoted_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quoted_by', to='boards.post'),
        ),
        migrations.AddField(
            model_name='postquote',
            name='quoting_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes_made', to='boards.post'),
        ),
        migrations.AddField(
            model_name='threadtitlerevision',
            name='edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threadtitlerevision',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='title_revisions', to='boards.thread'),
        ),
        migrations.AddConstraint(
            model_name='postquote',
            constraint=models.UniqueConstraint(fields=('quoting_post', 'quoted_post'), name='one_quote_row_per_pair'),
        ),
    ]
