# Generated by Django 5.2.17 on 2026-10-04 02:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_dm_participation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='threadparticipant',
            name='one_participation_per_thread',
        ),
        migrations.AddConstraint(
            model_name='threadparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('thread', 'user'), name='one_active_participation'),
        ),
    ]
