# Generated by Django 5.2.17 on 2026-10-04 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_dm_participation_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='boards.post'),
        ),
    ]
