# Generated by Django 5.2.17 on 2026-10-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_avatar_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrevision',
            name='redaction_reason',
            field=models.TextField(blank=True),
        ),
    ]
