# Generated by Django 5.2.17 on 2026-10-04 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_custom_emoji_extra'),
        ('boards', '0008_custom_emoji'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemoji',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='customemoji',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'rejected'), _negated=True), fields=('name',), name='emoji_name_unique_unless_rejected'),
        ),
    ]
