# Generated by Django 5.2.17 on 2026-10-03 17:33

import core.immutability
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('vouching_notes', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('recommended', 'Recommended'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('declined', 'Declined')], default='recommended', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.role')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to=settings.AUTH_USER_MODEL)),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.role')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('tenured', 'Tenured'), ('transferred', 'Transferred'), ('sponsor_left', 'Sponsor Left'), ('sponsor_banned', 'Sponsor Banned'), ('member_removed', 'Member Removed')], max_length=16)),
                ('is_original', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsorships', to=settings.AUTH_USER_MODEL)),
                ('previous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next', to='sponsorship.sponsorship')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsorships_given', to=settings.AUTH_USER_MODEL)),
                ('sponsor_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.role')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('ended_at__isnull', True)), fields=['sponsor'], name='sponsorship_active_by_sponsor')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('member',), name='one_active_sponsorship_per_member'), models.UniqueConstraint(condition=models.Q(('is_original', True)), fields=('member',), name='one_original_sponsorship_per_member'), models.CheckConstraint(condition=models.Q(('sponsor', models.F('member')), _negated=True), name='no_self_sponsorship')],
            },
            bases=(core.immutability.HistoryRowMixin, models.Model),
        ),
    ]
