# Generated by Django 5.2.17 on 2026-10-03 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_assignment_and_session_links'),
        ('sponsorship', '0002_invitation_waitlisted_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['recommended', 'reviewed'])), fields=('member',), name='one_open_promotion_per_member'),
        ),
    ]
