# Generated by Django 5.2.17 on 2026-10-03 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0003_one_open_promotion_per_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('waitlisted', 'Waitlisted'), ('approved', 'Approved'), ('declined', 'Declined'), ('invitee_declined', 'Invitee Declined'), ('rescinded', 'Rescinded'), ('expired', 'Expired')], default='pending', max_length=16),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['sponsor', 'created_at'], name='sponsorship_sponsor_7cbce5_idx'),
        ),
    ]
