# Generated by Django 5.2.17 on 2026-10-04 05:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0004_invitation_onboarding_states'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(choices=[('sponsor_left', 'Sponsor Left'), ('sponsor_banned', 'Sponsor Banned'), ('sponsor_role_lost', 'Sponsor Role Lost'), ('sponsor_lapse_restricted', 'Sponsor Lapse Restricted'), ('sponsor_review', 'Sponsor Review')], max_length=24)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('resumed', 'Resumed'), ('decided', 'Decided')], default='open', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, choices=[('admin_sponsored', 'Admin Sponsored'), ('extended', 'Extended'), ('removed', 'Removed')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsorship_transfers', to=settings.AUTH_USER_MODEL)),
                ('new_sponsorship', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_into', to='sponsorship.sponsorship')),
                ('sponsorship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='sponsorship.sponsorship')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorshipOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vouching_notes', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('lapsed', 'Lapsed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('offerer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsorship_offers', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='sponsorship.sponsorshiptransfer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sponsorshiptransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('member',), name='one_open_transfer_per_member'),
        ),
        migrations.AddConstraint(
            model_name='sponsorshipoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('transfer', 'offerer'), name='one_open_offer_per_offerer'),
        ),
    ]
