# Generated by Django 5.2.17 on 2026-10-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0005_sponsorship_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('tenured', 'Tenured'), ('transferred', 'Transferred'), ('sponsor_left', 'Sponsor Left'), ('sponsor_banned', 'Sponsor Banned'), ('member_removed', 'Member Removed'), ('member_left', 'Member Left')], max_length=16),
        ),
    ]
