# Generated by Django 5.2.17 on 2026-10-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0007_vouch_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitee_confirmed_adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='sponsor_confirmed_adult',
            field=models.BooleanField(default=False),
        ),
    ]
